# Generated by Django 3.0.7 on 2020-06-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=15)),
                ('link', models.CharField(max_length=1000)),
                ('store', models.CharField(max_length=100)),
                ('imageURL', models.CharField(max_length=1000)),
                ('logo', models.CharField(max_length=1000)),
            ],
        ),
    ]
