# Generated by Django 3.0.7 on 2020-06-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='input',
            name='message',
        ),
        migrations.RemoveField(
            model_name='input',
            name='store',
        ),
    ]
