# Generated by Django 3.0.7 on 2020-06-28 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20200628_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='input',
        ),
    ]
