# Generated by Django 3.0.7 on 2020-06-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='items',
            field=models.CharField(max_length=100),
        ),
    ]
