# Generated by Django 3.0.7 on 2020-06-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20200628_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='items',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
