# Generated by Django 3.0.7 on 2020-06-29 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_remove_input_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Input'),
        ),
    ]
