# Generated by Django 3.0.7 on 2020-06-29 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_auto_20200628_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='input',
        ),
        migrations.DeleteModel(
            name='Input',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
