# Generated by Django 3.0.7 on 2020-06-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_auto_20200628_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='input',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='imageURL',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='item',
            name='logo',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='store',
            field=models.CharField(max_length=500),
        ),
    ]
