export const FETCH_INPUT_REQUEST_POST = "FETCH_INPUT_REQUEST_POST";
export const FETCH_INPUT_REQUEST_GET = "FETCH_INPUT_REQUEST_GET";
export const FETCH_INPUT_SUCCESS_POST = "FETCH_INPUT_SUCCESS_POST";
export const FETCH_INPUT_SUCCESS_GET = "FETCH_INPUT_SUCCESS_GET";
export const FETCH_INPUT_ERROR_POST = "FETCH_INPUT_ERROR_POST";
export const FETCH_INPUT_ERROR_GET = "FETCH_INPUT_ERROR_GET";
